# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(030000)
$foreground = rgb(E6A2B9)
$color0 = rgb(030000)
$color1 = rgb(852749)
$color2 = rgb(732F87)
$color3 = rgb(853867)
$color4 = rgb(8F4059)
$color5 = rgb(914311)
$color6 = rgb(8B5267)
$color7 = rgb(CF8DA4)
$color8 = rgb(945A6F)
$color9 = rgb(852749)
$color10 = rgb(732F87)
$color11 = rgb(853867)
$color12 = rgb(8F4059)
$color13 = rgb(914311)
$color14 = rgb(8B5267)
$color15 = rgb(DFBEC9)
