# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch (user overrides)

# Auto-hide waybar on fullscreen
exec-once = $HOME/.config/hypr/scripts/AutoHideWaybar.sh

# Per-workspace One Piece wallpapers
exec-once = $HOME/.config/hypr/UserScripts/WorkspaceWallpaper.sh
