# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E6A2B9
background         #030000
cursor             #BC7265

active_tab_foreground     #030000
active_tab_background     #E6A2B9
inactive_tab_foreground   #E6A2B9
inactive_tab_background   #030000

active_border_color   #E6A2B9
inactive_border_color #030000
bell_border_color     #852749

color0      #030000
color1		#852749
color2		#732F87
color3		#853867
color4		#8F4059
color5		#914311
color6		#8B5267
color7		#CF8DA4
color8		#945A6F
color9		#852749
color10		#732F87
color11		#853867
color12		#8F4059
color13		#914311
color14		#8B5267
color15		#DFBEC9
